/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * startupUI/loading/loadingView.ls
 */
export class LoadingViewBase extends Laya.Scene {
    public context!: Laya.GTextField;
    public "process-bar"!: Laya.GProgressBar;
}

