/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * startupUI/login/loginView.ls
 */
export class LoginViewBase extends Laya.Scene {
    public loginPanel!: Laya.GBox;
    public input!: Laya.GTextInput;
    public confirmBtn!: Laya.GImage;
}

