/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * ui/mainscene/MainSceneView.ls
 */
export class MainSceneViewBase extends Laya.Scene {
    public playerProfile!: Laya.GBox;
    public btn_list!: Laya.GList;
}

