/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */

import { TopPrefab } from "./TopPrefab";

/**
 * ui/mainscene/MainSceneView.ls
 */
export class MainSceneViewBase extends Laya.Scene {
    public playerProfile!: TopPrefab;
    public btn_list!: Laya.GList;
}

