/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * ui/mainscene/playerProfile.lh
 */
export class TopPrefabBase extends Laya.GBox {
    public playerAvatar!: Laya.GLoader;
    public playerLevel!: Laya.GTextField;
    public playerName!: Laya.GTextField;
    public crystalAmount!: Laya.GTextField;
    public goldAmount!: Laya.GTextField;
    public staminaAmount!: Laya.GTextField;
}
