/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Startup.ls
 */
export class StartUpViewBase extends Laya.Scene {
    public animText!: Laya.GTextField;
}

